### ISSUE TITLE
API DX

### ISSUE THREAD

**Issue by DavidLiedle** [ezsystems/ezplatform#160]
Contains, but potentially not limited to improvements on:

- Languages (goal: avoid having to use translation helpers)
  - If language is not provided take SiteAccess languages into account before falling back to main language, all over
  - Only load one language, threat language params as priority like now on search
  - Reflect this on ContentInfo name as well
- Multi get support for all/most domain objects for optimized lookups (should also take into account language api changes from above)
  - Need to define how these should work when a item is not existing, maybe methods let user code specify if exception should be thrown or if value should be missing (default) for optimal user code
- Native Location drafts (goal: get rid of preview issues)
  - (however needs to make sure queries using data from this draft works as expected, with workspaces children should be query able for instance)
- Visibility (goal: move to permissions to get rid of boilerplate code)
- Site knowledge (goal: somehow natively take care about path prefixes and such)
  - Open question is how to avoid having to do with and withouth lookups for UrlAlias lookups.
- Domain Types (Like Object Wrapper, allow more logic to be moved to type as opposed to templates, examples: Asset, Site,..)
- For further use cases see Kaliop ObjectWrapper, NetGen SiteAPI, ... for instance consider to introduce content TypeInfo that is attached to ContentInfo

**Comment by DavidLiedle** [comment]
@andrerom Proposed to replace https://jira.ez.no/browse/EZP-26519

**Comment by andrerom** [comment]
Todo: Move to specs repo :)

**Comment by andrerom** [comment]
Moved to https://github.com/ezsystems/specs/issues/15
