### ISSUE TITLE
Encodung problems

### ISSUE THREAD

**Issue by DrMom161** [ezsystems/ezplatform#161]
Hello. I use Ez Platform for my Russian project, and I have a problem.
When I try save long location object name (more then 82 sigh) in cyrillic I receive a database error about wrong encoding. Example, "1 сентября Министерство экологии крепко возьмется за московских дачников и их скважины".
I found the error place - it is using "substr" instead of "mb_substr" (substr for multi-byte).
Please fix this bug for next release.
File: /vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Repository/Helper/NameSchemaService.php
Line: 205
name = rtrim(substr($name, 0, $this->settings['limit'] - strlen($this->settings['sequence']))) . $this->settings['sequence'];

**Comment by andrerom** [comment]
Hi @DrMom161 

would you be able  to suggest the change you know works here:
https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Repository/Helper/NameSchemaService.php#L205

Click on the edit icon on the top to edit and suggest a change *(Pull Request)*.

**Comment by yannickroger** [comment]
We do not use github as a bug tracker for the project (at least yet).
Please report this issue on https://jira.ez.no so we can investigate it shortly.
