### ISSUE TITLE
Admin panel shows different date in The Date FieldType for users in different timezone

### ISSUE THREAD

**Issue by alekseyh-hyuna** [ezsystems/ezplatform#162]
When users from USA create content with The Date FieldType, admin panel showed this field for him with wrong date (-1 day). For example, when he create content with date 20.11.2016, that content showed for him with date - 19.11.2016.
This problem is only in admin panel, and only for users from USA.
Server located in different timezone.

**Comment by yannickroger** [comment]
We do not use github as a bug tracker for the project (at least yet).
Please report this issue on https://jira.ez.no
As you are having issues with the admin panel, add "Platform UI" as the component affected by the bug. We will investigate the problem (I wrote that part of the code :) )
